### ISSUE TITLE
Featuring your work on the Jetson Community Projects page

### ISSUE THREAD

**Issue by efbsolis** [Mainamathenge/Pneumatic_leakage-JETSON-NANO#1]
Hi!

My name is Eamon and I'm part of the NVIDIA Jetson team.
We saw your project we'd love to show your work on our Jetson Community Projects page:
https://developer.nvidia.com/embedded/community/jetson-projects

I looked for ways to reach out to you to let you know about it, but I wasn't able to find a way other than this.
Let me know if this interests you--I'll send you my work email where we can talk.

Thank you so much, and be well!
Eamon

**Comment by Mainamathenge** [comment]
Hello Eamon
Thanks for reaching out to me
I am interested please
you can just send the work email

**Comment by efbsolis** [comment]
Hi!

Please contact me at ebohan@nvidia.com

Thank you!
Eamon
